# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

# .travis.yml

language: r
sudo: FALSE
warnings_are_errors: true

env:
 global:
   - CRAN: http://cran.rstudio.com


before_cache: Rscript -e 'remotes::install_cran("pkgdown")'
deploy:
  provider: script
  script: Rscript -e 'pkgdown::deploy_site_github()'
  skip_cleanup: true

notifications:
  email:
    on_success: change
    on_failure: change
